---
# Start node-exporter service
- name: Start node-exporter service
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ node_exporter_name }}"
    state: present
  register: node_exporter_service
  retries: 5
  delay: 10
  until: node_exporter_service.services[node_exporter_name][node_exporter_name].state.running
  notify:
    - Check node-exporter service

# Restart node-exporter service
- name: Restart node-exporter service
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ node_exporter_name }}"
    state: present
    restarted: true
  notify:
    - Check node-exporter service

# Check node-exporter service
- name: Check node-exporter service
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ node_exporter_port }}"
    method: GET
    status_code: 200
  register: node_exporter_status
  until: node_exporter_status.status == 200
  retries: 3
  delay: 30
