---
# Service root path
service_root_path: "/opt/docker_services"

# Docker configuration
docker_group: "docker"
docker_restart_policy: "always"

# Default timezone
timezone: "Europe/Moscow"

# Nextcloud configuration
# https://nextcloud.com/
# https://hub.docker.com/_/nextcloud
nextcloud_name: "nextcloud"
nextcloud_image: "nextcloud"
nextcloud_tag: "25.0.9-apache"
nextcloud_web_port: "8050"
nextcloud_trusted_domains: ["{{ ansible_host }}"]
nextcloud_admin_username: "nextcloud"
nextcloud_admin_password: "nextcloud"
nextcloud_db_type: "pgsql"
nextcloud_db_address: "{{ ansible_host }}:{{ postgres_port }}"
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"
nextcloud_db_password: "nextcloud"
