---
# Create grafana folder
- name: Create grafana folder
  become: true
  ansible.builtin.file:
    path: "{{ service_root_path }}/{{ grafana_name }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "dashboards"
    - "provisioning/dashboards"
    - "provisioning/datasources"

# Create grafana datasources and dashboards
- name: Create grafana datasources and dashboards
  become: true
  ansible.builtin.template:
    src: "grafana_{{ item }}.j2"
    dest: "{{ service_root_path }}/{{ grafana_name }}/provisioning/{{ item }}/{{ item }}.yaml"
    mode: "0644"
  loop:
    - "dashboards"
    - "datasources"
  notify:
    - Restart grafana service

# Install grafana dashboards
- name: Install grafana dashboards
  become: true
  ansible.builtin.get_url:
    url: "https://grafana.com/api/dashboards/{{ item.dashboard_id }}/revisions/{{ item.revision_id }}/download"
    dest: "{{ service_root_path }}/{{ grafana_name }}/dashboards/{{ item.name }}_{{ item.dashboard_id }}.json"
    mode: "0644"
  loop: "{{ grafana_dashboards }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart grafana service

# Create grafana docker-compose file
- name: Create grafana docker-compose file
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ service_root_path }}/{{ grafana_name }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Start grafana service
