---

- name: config | grafana datasources and dashboards folders
  become: true
  ansible.builtin.file:
    path: '{{ grafana_docker_config.path }}/provisioning/{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - dashboards
    - datasources

- name: config | grafana datasources and dashboards
  become: true
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ grafana_docker_config.path }}/provisioning/{{ item }}/{{ item }}.yaml'
    mode: '0644'
    lstrip_blocks: true
  loop:
    - dashboards
    - datasources
  notify:
    - grafana | restart container

- name: config | grafana datasources and dashboards folders
  become: true
  ansible.builtin.file:
    path: '{{ grafana_docker_config.path }}/dashboards'
    state: directory
    mode: '0755'

- name: config | grafana dashboards
  become: true
  ansible.builtin.get_url:
    url: https://grafana.com/api/dashboards/{{ item.dashboard_id }}/revisions/{{ item.revision_id }}/download
    dest: '{{ grafana_docker_config.path }}/dashboards/{{ item.name }}_{{ item.dashboard_id }}.json'
    mode: '0644'
  loop: '{{ grafana_dashboards }}'
  loop_control:
    label: '{{ item.name }}'
  notify:
    - grafana | restart container
