---

- name: detect | grafana container
  become: true
  community.docker.docker_container_info:
    name: '{{ grafana_docker_config.name }}'
  register: grafana_container

- name: detect | set grafana_container_exists fact
  ansible.builtin.set_fact:
    grafana_container_exists: '{{ true if grafana_container.exists else false }}'

- name: detect | set grafana_container_update fact
  ansible.builtin.set_fact:
    grafana_container_update: >-
      {{ true if
      grafana_container.exists and
      grafana_docker_config.tag not in grafana_container.container.Config.Image
      else false }}
