---

- name: detect | services
  ansible.builtin.service_facts:

- name: detect | grafana container
  community.docker.docker_container_info:
    name: '{{ grafana_name }}'
  register: grafana_container

- name: detect | grafana container exists fact
  ansible.builtin.set_fact:
    grafana_container_exists: '{{ true if grafana_container.exists else false }}'

- name: detect | grafana container update fact
  ansible.builtin.set_fact:
    grafana_container_update: >
      {{ true if grafana_container.exists and grafana_tag not in grafana_container.container.Config.Image else false }}
