namespace: "flyoverhead"
name: "docker"
version: 1.0.0
readme: README.md
authors: ["flyoverhead"]
description: Ansible collection for docker services deployment
license: ["GPL-3.0-only"]
tags: ["docker", "services"]
dependencies:
  "community.docker": ">=3.4.3"

# The URL of the originating SCM repository
repository: https://github.com/flyoverhead/docker-services

# The URL to the collection issue tracker
issues: https://github.com/flyoverhead/docker-services/issues
