---

namespace: flyoverhead
name: docker
version: 1.1.0
readme: README.md
authors:
  - flyoverhead
description: Ansible collection for docker services deployment
license:
  - GPL-3.0-only
tags:
  - linux
  - monitoring
  - networking
  - tools
dependencies:
  community.docker: '>=3.4.3'

repository: https://github.com/flyoverhead/docker-services
issues: https://github.com/flyoverhead/docker-services/issues
