---

version: '3'

silent: true

tasks:

  play:
    dir: tests
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml

  reload:
    dir: tests
    cmds:
      - ansible -i inventory.yml all -m ansible.builtin.reboot --become

  start:
    dir: tests
    cmds:
      - vagrant up
      - task: play

  stop:
    dir: tests
    cmds:
      - vagrant destroy -f
      - rm -rf .vagrant || True

  update:
    dir: tests
    cmds:
      - vagrant box update
      - vagrant box prune
