---

galaxy_info:
  role_name: singbox
  namespace: flyoverhead
  author: flyoverhead
  description: Sing-box VPN docker service deployment
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - docker
    - networking
    - proxy
    - vpn

dependencies: []
