---
# Create torrserver folder
- name: Create torrserver folder
  become: true
  ansible.builtin.file:
    path: "{{ service_root_path }}/{{ torrserver_name }}"
    state: directory
    mode: "0755"

# Create torrserver docker-compose file
- name: Create torrserver docker-compose file
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ service_root_path }}/{{ torrserver_name }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Start torrserver service
