---

- name: detect | torrserver container
  become: true
  community.docker.docker_container_info:
    name: '{{ torrserver_docker_config.name }}'
  register: torrserver_container

- name: detect | set torrserver_container_exists fact
  ansible.builtin.set_fact:
    torrserver_container_exists: '{{ true if torrserver_container.exists else false }}'

- name: detect | set torrserver_container_update fact
  ansible.builtin.set_fact:
    torrserver_container_update: >-
      {{ true if
      torrserver_container.exists and
      torrserver_docker_config.tag not in torrserver_container.container.Config.Image
      else false }}
