---
# Check current torrserver service if exists
- name: Check torrserver container
  community.docker.docker_container_info:
    name: "{{ torrserver_name }}"
  register: torrserver_service
  changed_when: >
    not torrserver_service.exists or
    torrserver_tag not in torrserver_service.container.Config.Image
  failed_when: torrserver_service.exists and torrserver_service.container.State.ExitCode != 0
  notify:
    - Start torrserver service

# Configure torrserver service
- name: Configure torrserver service
  ansible.builtin.include_tasks: configure.yml

# Deploy torrserver service
- name: Deploy torrserver service
  ansible.builtin.meta: flush_handlers
