---

- name: update | torrserver docker-compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ torrserver_docker_config.path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0644'
    lstrip_blocks: true
  notify:
    - torrserver | recreate container
