---
# Service root path
service_root_path: "/opt/docker_services"

# Docker configuration
docker_restart_policy: "always"
docker_network_mode: "host"

# Default timezone
timezone: "Europe/Moscow"

# Node exporter configuration
# https://github.com/prometheus/node_exporter
# https://hub.docker.com/r/prom/node-exporter
node_exporter_name: "node-exporter"
node_exporter_image: "prom/node-exporter"
node_exporter_tag: "v1.6.1"
node_exporter_port: "9100"
node_exporter_command:
  [
    "--path.procfs=/host/proc",
    "--path.rootfs=/rootfs",
    "--path.sysfs=/host/sys",
    "--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($$|/)",
  ]
