---

# https://github.com/prometheus/node_exporter
# https://hub.docker.com/r/prom/node-exporter/tags

node_exporter_docker_config:
  name: node-exporter
  image: prom/node-exporter
  tag: v1.8.2
  path: '{{ docker_path }}/node-exporter'
  restart_policy: '{{ docker_restart_policy }}'
  network_mode: '{{ docker_network_mode }}'
  timezone: '{{ docker_timezone }}'

node_exporter_service_config:
  listening_address: 0.0.0.0
  listening_port: 9100

node_exporter_command:
  - >-
    --web.listen-address={{ node_exporter_service_config.listening_address
    }}:{{ node_exporter_service_config.listening_port }}
  - --path.procfs=/host/proc
  - --path.rootfs=/rootfs
  - --path.sysfs=/host/sys
  - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($$|/)
