---
# Service root path
service_root_path: "/opt/docker_services"

# Docker configuration
docker_group: "docker"
docker_restart_policy: "always"
docker_network_mode: "host"

# Default timezone
timezone: "Europe/Moscow"

# Gitea configuration
# https://docs.gitea.io/en-us/
# https://hub.docker.com/r/gitea/gitea
gitea_name: "gitea"
gitea_image: "gitea/gitea"
gitea_tag: "1.20.3"
gitea_web_port: "8020"
gitea_ssh_port: "2222"
gitea_domain: "{{ ansible_host }}"
gitea_git_uid: "1050"
gitea_git_gid: "1050"
gitea_admin_username: "gitea"
gitea_admin_password: "gitea"
gitea_admin_email: "email@example.com"
gitea_db_type: "postgres"
gitea_db_address: "{{ ansible_host }}:{{ postgres_port }}"
gitea_db_name: "gitea"
gitea_db_user: "gitea"
gitea_db_password: "gitea"
gitea_web_theme: "arc-green"
