---

# https://sing-box.sagernet.org
# https://github.com/SagerNet/sing-box/tags

singbox_docker_config:
  name: sing-box
  image: ghcr.io/sagernet/sing-box
  tag: v1.12.1
  path: '{{ docker_path }}/sing-box'
  restart_policy: always
  network_mode: host
  timezone: Europe/Moscow

singbox_server_config:
  name: '{{ inventory_hostname }}'
  listening_address: 0.0.0.0
  listening_port: 443
  public_address: '{{ ansible_host }}'
  vless_address: npo.nl
  vless_port: 443
  dns:
    servers: []
      # - tag: dns-local
      #   address: local
      #   detour: out-direct
      # - tag: dns-wg
      #   address: 192.168.1.1
      #   detour: out-wg
      # - tag: dns-direct
      #   address: https://common.dot.dns.yandex.net
      #   address_resolver: dns-local
      #   detour: out-direct
    rules: []
      # - outbound: out-direct
      #   server: dns-direct
      # - outbound: out-wg
      #   server: dns-wg
    # final: dns-local
    # strategy: ipv4_only
    # independent_cache: true
  endpoints: []
    # - tag: out-wg
    #   type: wireguard
    #   system: true
    #   name: wg0
    #   address:
    #     - 192.168.1.2/32
    #   private_key: <private_key>
    #   listen_port: 51832
    #   peers:
    #     - address: <peer_ip_address>
    #       port: 51832
    #       public_key: <peer_public_key>
    #       allowed_ips:
    #         - 192.168.1.0/24
    #       persistent_keepalive_interval: 25
  outbounds: []
    # - type: direct
    #   tag: out-direct
  route:
    rules: []
      # - inbound: tun-in
      #   action: sniff
      # - protocol: dns
      #   action: hijack-dns
      # - domain:
      #     - home.lab
      #   outbound: out-wg
      # - rule_set:
      #     - geosite-category-ads
      #   action: reject
    rule_set: []
      # - tag: geosite-category-ads
      #   type: remote
      #   format: binary
      #   url: https://raw.githubusercontent.com/sagernet/sing-geosite/rule-set/geosite-category-ads.srs
    default_domain_resolver:
      server: local
    final: out-direct
    auto_detect_interface: true
  log:
    level: error
    output: box.log
    timestamp: true

singbox_clients_config:
  path: '{{ inventory_dir }}/files/clients'
  clients:
    - name: keenetic_router
    - name: smartphone
      platform: android
    - name: iphone
      platform: ios
    - name: macbook
      platform: macos
  dns:
    servers: []
      # - tag: dns-direct
      #   address: local
      #   detour: out-direct
      # - tag: dns-proxy
      #   address: https://dns.adguard-dns.com/dns-query
      #   address_resolver: dns-direct
      #   detour: out-proxy
    rules: []
    #   - outbound: out-direct
    #     server: dns-direct
    #   - domain_keyword:
    #       - example
    #     server: dns-proxy
    #   - rule_set:
    #       - geoip-ru
    #       - geosite-category-gov-ru
    #       - geosite-category-ru
    #     server: dns-proxy
    final: dns-direct
    strategy: ipv4_only
    independent_cache: true
  inbounds: []
    # - type: tun
    #   tag: tun-in
    #   interface_name: tun0
    #   address: 172.18.0.1/30
    #   auto_route: true
  outbounds: []
    # - type: vless
    #   tag: out-nl
    #   server: '{{ ansible_host }}'
    #   server_port: 443
    #   uuid: '{{ item.uuid | default("") }}'
    #   flow: xtls-rprx-vision
    #   tls:
    #     enabled: true
    #     server_name: youtube.com
    #     utls:
    #       enabled: true
    #       fingerprint: chrome
    #     reality:
    #       enabled: true
    #       public_key: '{{ singbox_server_config.public_key | default("") }}'
    #       short_id: '{{ item.short_id | default("") }}'
    #   domain_resolver:
    #     server: dns-proxy
    # - type: direct
    #   tag: out-direct
    #   domain_resolver:
    #     server: dns-direct
  endpoints: []
    # - tag: out-wg
    #   type: wireguard
    #   system: true
    #   name: wg0
    #   address:
    #     - 192.168.1.2/32
    #   private_key: <private_key>
    #   listen_port: 51832
    #   peers:
    #     - address: <peer_ip_address>
    #       port: 51832
    #       public_key: <peer_public_key>
    #       allowed_ips:
    #         - 192.168.1.0/24
    #       persistent_keepalive_interval: 25
  route:
    rules:
      # - inbound: tun-in
      #   action: sniff
      # - protocol: dns
      #   action: hijack-dns
      # - domain:
      #     - example.com
      #   outbound: out-proxy
      # - domain_regex:
      #     - example.+
      #   outbound: out-proxy
      # - rule_set:
      #     - geosite-category-ads
      #   action: reject
    rule_set:
      - tag: geosite-category-ads
        type: remote
        format: binary
        url: https://raw.githubusercontent.com/sagernet/sing-geosite/rule-set/geosite-category-ads.srs
    default_domain_resolver:
      server: dns-direct
    auto_detect_interface: true
  log:
    level: error
    timestamp: true

singbox_tuning_config:
  enabled: true
  fs.file-max: 51200
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.core.rmem_max: 67108864
  net.core.wmem_max: 67108864
  net.core.netdev_max_backlog: 250000
  net.core.somaxconn: 4096
  net.ipv4.tcp_syncookies: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_fin_timeout: 30
  net.ipv4.tcp_keepalive_time: 1200
  net.ipv4.ip_local_port_range: 10000 65000
  net.ipv4.tcp_keepalive_probes: 5
  net.ipv4.tcp_keepalive_intvl: 30
  net.ipv4.tcp_max_syn_backlog: 8192
  net.ipv4.tcp_max_tw_buckets: 5000
  net.ipv4.tcp_fastopen: 3
  net.ipv4.tcp_mem: 25600 51200 102400
  net.ipv4.udp_mem: 25600 51200 102400
  net.ipv4.tcp_rmem: 4096 87380 67108864
  net.ipv4.tcp_wmem: 4096 65536 67108864
  net.ipv4.tcp_mtu_probing: 1
  net.ipv4.tcp_slow_start_after_idle: 0
  system_limits:
    - limit: nofile
      domain: '*'
      types:
        - type: soft
          value: 51200
        - type: hard
          value: 51200

singbox_force_update_secrets: false
