---

- name: docker | start service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: docker | reload groups
  ansible.builtin.meta: reset_connection
