---

galaxy_info:
  role_name: torrserver
  namespace: flyoverhead
  author: flyoverhead
  description: TorrServer docker service deployment
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - docker
    - media
    - streaming
    - torrent

dependencies: []
