---
# Start gitea service
- name: Start gitea service
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ gitea_name }}"
    state: present
  register: gitea_service
  retries: 5
  delay: 10
  until: gitea_service.services[gitea_name][gitea_name].state.running
  notify:
    - Check gitea service

# Restart gitea service
- name: Restart gitea service
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ gitea_name }}"
    state: present
    restarted: true
  notify:
    - Check gitea service

# Check gitea service
- name: Check gitea service
  ansible.builtin.uri:
    url: "http://{{ gitea_domain }}:{{ gitea_web_port }}"
    method: GET
    status_code: 200
  register: gitea_status
  until: gitea_status.status == 200
  retries: 3
  delay: 30

# Reload connection to host after adding users
# to docker group for changes to take effect
- name: Reload groups
  ansible.builtin.meta: reset_connection

# Restart sshd systemd service unit
- name: Restart sshd service
  become: true
  ansible.builtin.service:
    name: "sshd"
    state: "restarted"
