---
# Start xray service
- name: Start xray service
  become: true
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ xray_name }}"
    state: present
  register: xray_service
  retries: 5
  delay: 10
  until: xray_service.services[xray_name][xray_name].state.running
  notify:
    - Check xray service

# Restart xray service
- name: Restart xray service
  become: true
  community.docker.docker_compose:
    project_src: "{{ service_root_path }}/{{ xray_name }}"
    state: present
    restarted: true
  notify:
    - Check xray service

# Check xray service
- name: Check xray service
  become: true
  ansible.builtin.command:
    cmd: docker logs "{{ xray_name }}"
  register: xray_status
  failed_when: |
    'started' not in xray_status.stderr and
    'started' not in xray_status.stdout
  changed_when: false
