---
# Check current nextcloud service if exists
- name: Check nextcloud container
  community.docker.docker_container_info:
    name: "{{ nextcloud_name }}"
  register: nextcloud_service
  changed_when: >
    not nextcloud_service.exists or
    nextcloud_tag not in nextcloud_service.container.Config.Image
  failed_when: nextcloud_service.exists and nextcloud_service.container.State.ExitCode != 0
  notify:
    - Start nextcloud service

# Configure nextcloud service
- name: Configure nextcloud service
  ansible.builtin.include_tasks: configure.yml

# Deploy nextcloud service
- name: Deploy nextcloud service
  ansible.builtin.meta: flush_handlers
