---
# Check current drone-runner service if exists
- name: Check drone-runner container
  community.docker.docker_container_info:
    name: "{{ drone_runner_name }}"
  register: drone_runner_service
  changed_when: >
    not drone_runner_service.exists or
    drone_runner_tag not in drone_runner_service.container.Config.Image
  failed_when: drone_runner_service.exists and drone_runner_service.container.State.ExitCode != 0
  notify:
    - Start drone-runner service

# Install drone-runner service
- name: Configure drone-runner service
  ansible.builtin.include_tasks: configure.yml

# Deploy drone-runner service
- name: Deploy drone-runner service
  ansible.builtin.meta: flush_handlers
