---

- name: detect | sing-box docker
  tags:
    - singbox.docker
  block:

    - name: detect | sing-box container
      community.docker.docker_container_info:
        name: '{{ singbox_docker_config.name }}'
      register: singbox_container

    - name: detect | set singbox_container_exists fact
      ansible.builtin.set_fact:
        singbox_container_exists: >-
          {{ true if
          singbox_container.exists
          else false }}

    - name: detect | set singbox_container_update fact
      ansible.builtin.set_fact:
        singbox_container_update: >-
          {{ true if
          singbox_container.exists and
          singbox_docker_config.tag not in singbox_container.container.Config.Image
          else false }}

- name: detect | database
  tags:
    - singbox.clients
    - singbox.server
  block:

    - name: detect | check database file
      ansible.builtin.stat:
        path: '{{ singbox_docker_config.path }}/config.json'
      register: singbox_database_file

    - name: detect | check public key file
      ansible.builtin.stat:
        path: '{{ singbox_docker_config.path }}/public_key'
      register: singbox_public_key_file

    - name: detect | read database file
      become: true
      ansible.builtin.slurp:
        src: '{{ singbox_docker_config.path }}/config.json'
      register: singbox_slurp_database_file
      when:
        - singbox_database_file.stat.exists

    - name: detect | read public key file
      become: true
      ansible.builtin.slurp:
        src: '{{ singbox_docker_config.path }}/public_key'
      register: singbox_slurp_public_key_file
      when:
        - singbox_public_key_file.stat.exists

    - name: detect | set singbox_database_file_content fact
      ansible.builtin.set_fact:
        singbox_database_file_content: >-
          {{ singbox_slurp_database_file.content | b64decode |
          from_json | json_query("inbounds")
          if singbox_database_file.stat.exists
          else '' }}
        singbox_public_key_file_content: >-
          {{ singbox_slurp_public_key_file.content | b64decode
          if singbox_public_key_file.stat.exists
          else '' }}

    - name: detect | set singbox_private_key fact
      ansible.builtin.set_fact:
        singbox_private_key: >-
          {{ singbox_database_file_content |
          selectattr('tls', 'search', singbox_server_config.vless_address) |
          map(attribute='tls.reality.private_key') | join('') }}

    - name: detect | set singbox_public_key fact
      ansible.builtin.set_fact:
        singbox_public_key: >-
          {{ singbox_public_key_file_content }}

    - name: detect | set singbox_server_keys_exists fact
      ansible.builtin.set_fact:
        singbox_server_keys_exists: >-
          {{ true if
          singbox_private_key | default('') | length > 0
          and
          singbox_public_key | default('') | length > 0
          else false }}

    - name: detect | get sing-box database facts
      when:
        - singbox_database_file_content | length > 0
      block:

        - name: detect | set singbox_active_clients fact
          ansible.builtin.set_fact:
            singbox_active_clients: >-
              {{ singbox_active_clients | default([]) +
              [item | combine({'short_id': (singbox_database_file_content |
              map(attribute='tls.reality.short_id') | flatten)[singbox_client]})] }}
          loop: >-
            {{ singbox_database_file_content |
            selectattr('tls', 'search', singbox_server_config.vless_address) |
            map(attribute='users') | flatten }}
          loop_control:
            label: '{{ item.name }}'
            index_var: singbox_client

        - name: detect | set singbox_inactive_clients fact
          ansible.builtin.set_fact:
            singbox_inactive_clients: >-
              {{ singbox_active_clients | default([]) |
              rejectattr('name', 'in', singbox_clients_config.clients) }}

    - name: detect | set singbox_new_clients fact
      ansible.builtin.set_fact:
        singbox_new_clients: >-
          {{ singbox_clients_config.clients
          if
          singbox_force_update_secrets
          else
          singbox_clients_config.clients |
          difference(singbox_active_clients |
          default([]) | map(attribute='name')) }}
