---

- name: config | alertmanager configuration file
  become: true
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: '{{ alertmanager_docker_config.path }}/alertmanager.yml'
    mode: '0644'
    lstrip_blocks: true
  notify:
    - alertmanager | restart container

- name: config | alertmanager message template
  block:

    - name: config | alertmanager message template folder
      become: true
      ansible.builtin.file:
        path: '{{ alertmanager_docker_config.path }}/templates'
        state: directory
        mode: '0755'

    - name: config | alertmanager message template files
      become: true
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: '{{ alertmanager_docker_config.path }}/templates/{{ item | basename }}'
        mode: '0644'
      with_fileglob:
        - '*.tmpl'
      loop_control:
        label: '{{ item | basename }}'
      notify:
        - alertmanager | restart container
