---

- name: detect | alertmanager container
  community.docker.docker_container_info:
    name: '{{ alertmanager_name }}'
  register: alertmanager_container

- name: detect | alertmanager container exists fact
  ansible.builtin.set_fact:
    alertmanager_container_exists: '{{ true if alertmanager_container.exists else false }}'

- name: detect | alertmanager container update fact
  ansible.builtin.set_fact:
    alertmanager_container_update: >
      {{ true if alertmanager_container.exists and alertmanager_tag not in alertmanager_container.container.Config.Image else false }}
