---

- name: install | alertmanager service folder
  become: true
  ansible.builtin.file:
    path: '{{ alertmanager_docker_config.path }}'
    state: directory
    mode: '0755'

- name: install | alertmanager docker-compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ alertmanager_docker_config.path }}/docker-compose.yml'
    mode: '0644'
    lstrip_blocks: true
  notify:
    - alertmanager | start container
