---
# Check current alertmanager service if exists
- name: Check alertmanager container
  community.docker.docker_container_info:
    name: "{{ alertmanager_name }}"
  register: alertmanager_service
  changed_when: >
    not alertmanager_service.exists or
    alertmanager_tag not in alertmanager_service.container.Config.Image
  failed_when: alertmanager_service.exists and alertmanager_service.container.State.ExitCode != 0
  notify:
    - Start alertmanager service

# Configure alertmanager service
- name: Configure alertmanager service
  ansible.builtin.include_tasks: configure.yml
  # when: not alertmanager_service.exists

# Deploy alertmanager service
- name: Deploy alertmanager service
  ansible.builtin.meta: flush_handlers
