---

- name: client | generate secrets
  when: >-
    (item.id | default('') | length == 0
    and
    item.short_id | default('') | length == 0)
    or xray_force_update_secrets
  block:

    - name: client | generate id
      become: true
      community.docker.docker_container:
        name: '{{ xray_docker_config.name }}'
        image: '{{ xray_docker_config.image }}:{{ xray_docker_config.tag }}'
        cleanup: true
        command: xray uuid
        detach: false
      register: xray_client_id_output
      changed_when: true

    - name: client | set id fact
      ansible.builtin.set_fact:
        generated_client_id: '{{ xray_client_id_output.container.Output | trim }}'

    - name: client | generate short id
      ansible.builtin.command:
        cmd: openssl rand -hex 8
      register: short_id_output
      changed_when: true

    - name: client | set short id fact
      ansible.builtin.set_fact:
        generated_client_short_id: '{{ short_id_output.stdout | trim }}'

- name: client | set id and short id facts
  ansible.builtin.set_fact:
    client_id: >-
      {{ generated_client_id if
      generated_client_id | default([]) | length > 0
      else item.id }}
    client_short_id: >-
      {{ generated_client_short_id if
      generated_client_short_id | default([]) | length > 0
      else item.short_id }}

- name: client | add secrets to clients config
  ansible.builtin.set_fact:
    xray_add_clients: >-
      {{ xray_add_clients | default([]) + [item |
      combine({'id': client_id, 'short_id': client_short_id})] }}
