---

- name: detect
  ansible.builtin.include_tasks: detect.yml

- name: install
  ansible.builtin.include_tasks: install.yml
  when:
    - not xray_container_exists

- name: update
  ansible.builtin.include_tasks: update.yml
  when:
    - xray_container_update

- name: config
  ansible.builtin.include_tasks: config.yml

- name: handlers
  ansible.builtin.meta: flush_handlers
