---

- name: config | generate server keys
  become: true
  community.docker.docker_container:
    name: '{{ xray_docker_config.name }}'
    image: '{{ xray_docker_config.image }}:{{ xray_docker_config.tag }}'
    cleanup: true
    command: xray x25519
    detach: false
  register: xray_keys

- name: config | set server keys fact
  ansible.builtin.set_fact:
    xray_private_key: >-
      {{ xray_keys.container.Output | regex_search('(?<=Private key: )(.*?)(?=\n)') }}
    xray_public_key: >-
      {{ xray_keys.container.Output | regex_search('(?<=Public key: )(.*?)(?=\n)') }}
  no_log: true
