---
# Create gitea folder
- name: Create gitea folder
  become: true
  ansible.builtin.file:
    path: "{{ service_root_path }}/{{ gitea_name }}"
    state: directory
    mode: "0755"

# Create gitea docker-compose file
- name: Create gitea docker-compose file
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ service_root_path }}/{{ gitea_name }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Start gitea service

# Start gitea service
- name: Start gitea service
  ansible.builtin.meta: flush_handlers
