---
# Check current gitea service if exists
- name: Check gitea container
  community.docker.docker_container_info:
    name: "{{ gitea_name }}"
  register: gitea_service
  changed_when: >
    not gitea_service.exists or
    gitea_tag not in gitea_service.container.Config.Image
  failed_when: gitea_service.exists and gitea_service.container.State.ExitCode != 0
  notify:
    - Start gitea service

# Prepare gitea environment
- name: Prepare gitea environment
  ansible.builtin.include_tasks: prepare.yml

# Initialize gitea service
- name: Initialize gitea service
  ansible.builtin.include_tasks: initialize.yml

# Configure gitea service
- name: Configure gitea service
  ansible.builtin.include_tasks: configure.yml

# Deploy gitea service
- name: Deploy gitea service
  ansible.builtin.meta: flush_handlers
