---

galaxy_info:
  role_name: grafana
  namespace: flyoverhead
  author: flyoverhead
  description: Grafana docker service deployment
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - dashboards
    - docker
    - monitoring

dependencies: []
