---

- name: detect
  ansible.builtin.include_tasks:
    file: detect.yml

- name: install
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not dnscrypt_container_exists

- name: update
  ansible.builtin.include_tasks:
    file: update.yml
  when:
    - dnscrypt_container_update

- name: config
  ansible.builtin.include_tasks:
    file: config.yml

- name: handlers
  ansible.builtin.meta: flush_handlers
