---
# Service root path
service_root_path: "/opt/docker_services"

# Docker configuration
docker_restart_policy: "always"

# Default timezone
timezone: "Europe/Moscow"

# Wireguard configuration
# https://docs.linuxserver.io/images/docker-wireguard
# https://hub.docker.com/r/linuxserver/wireguard
wireguard_name: "wireguard"
wireguard_image: "linuxserver/wireguard"
wireguard_tag: "v1.0.20210914-ls3"
wireguard_server_address: "192.168.1.1"
wireguard_server_port: "51820"
wireguard_internal_subnet: "10.13.13.0"
wireguard_allowed_ips: ["0.0.0.0/0"]
wireguard_peers: ["client01", "client02"]
wireguard_post_up: >-
  iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE
wireguard_post_down: >-
  iptables -t nat -D POSTROUTING -o wg+ -j MASQUERADE
