---
# Check current drone service if exists
- name: Check drone container
  community.docker.docker_container_info:
    name: "{{ drone_name }}"
  register: drone_service
  changed_when: >
    not drone_service.exists or
    drone_tag not in drone_service.container.Config.Image
  failed_when: drone_service.exists and drone_service.container.State.ExitCode != 0
  notify:
    - Start drone service

# Install drone service
- name: Configure drone service
  ansible.builtin.include_tasks: configure.yml

# Deploy drone service
- name: Deploy drone service
  ansible.builtin.meta: flush_handlers
