---

alertmanager:
  children:
    vps:

node_exporter:
  children:
    vps:

prometheus:
  children:
    vps:

timeweb:
  hosts:
    timeweb-ru:

vdsina:
  hosts:
    vdsina-nl:

vps:
  children:
    timeweb:
    vdsina:

xray:
  children:
    timeweb:
    vdsina:
