---
# Check current node-exporter service if exists
- name: Check node-exporter container
  community.docker.docker_container_info:
    name: "{{ node_exporter_name }}"
  register: node_exporter_service
  changed_when: >
    not node_exporter_service.exists or
    node_exporter_tag not in node_exporter_service.container.Config.Image
  failed_when: node_exporter_service.exists and node_exporter_service.container.State.ExitCode != 0
  notify:
    - Start node-exporter service

# Install node-exporter service
- name: Create node-exporter container
  ansible.builtin.include_tasks: configure.yml

# Deploy node-exporter service
- name: Deploy node-exporter service
  ansible.builtin.meta: flush_handlers
