---

# https://prometheus.io/docs/alerting/latest/alertmanager/
# https://hub.docker.com/r/prom/alertmanager/tags

alertmanager_docker_config:
  name: alertmanager
  image: prom/alertmanager
  tag: '{{ alertmanager_version }}'
  path: '{{ docker_path }}/alertmanager'
  restart_policy: '{{ docker_restart_policy }}'
  network_mode: '{{ docker_network_mode }}'
  timezone: '{{ docker_timezone }}'

alertmanager_service_config:
  listening_address: 0.0.0.0
  listening_port: 9093

alertmanager_command:
  - >-
    --web.listen-address={{ alertmanager_service_config.listening_address
    }}:{{ alertmanager_service_config.listening_port }}
  - --config.file=/etc/alertmanager/alertmanager.yml

alertmanager_global_config:
  resolve_timeout: 5m

alertmanager_route_config:
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 60m
  group_by:
    - alertname
  receiver: telegram

alertmanager_receivers_config:
  - name: telegram
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        bot_token: ''
        chat_id: ''
        message: '{% raw %}{{ template "telegram.custom.message" . }}{% endraw %}'
        parse_mode: Markdown
