---

# https://prometheus.io/docs/alerting/latest/alertmanager/
# https://hub.docker.com/r/prom/alertmanager
alertmanager_name: alertmanager
alertmanager_image: prom/alertmanager
alertmanager_tag: v0.27.0
alertmanager_listening_address: 127.0.0.1
alertmanager_listening_port: 9093
alertmanager_path: /opt/docker/alertmanager
alertmanager_restart_policy: always
alertmanager_network_mode: host
alertmanager_timezone: Europe/Moscow

alertmanager_command:
  - --web.listen-address={{ alertmanager_listening_address }}:{{ alertmanager_listening_port }}
  - --config.file=/etc/alertmanager/alertmanager.yml

alertmanager_global_config:
  resolve_timeout: 5m

alertmanager_route_config:
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 60m
  group_by:
    - alertname
  receiver: telegram

alertmanager_receivers_config:
  - name: telegram
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        bot_token: ''
        chat_id: ''
        message: '{% raw %}{{ template "telegram.custom.message" . }}{% endraw %}'
        parse_mode: Markdown
