---

galaxy_info:
  author: flyoverhead
  description: Dnscrypt-Proxy docker service deployment
  license: ISC
  min_ansible_version: '2.13'
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - dnscrypt

dependencies:
  - role: docker
