---
# Create prometheus folder
- name: Create prometheus folder
  become: true
  ansible.builtin.file:
    path: "{{ service_root_path }}/{{ prometheus_name }}/alerts"
    state: directory
    mode: "0755"

# Create prometheus configuration file
- name: Create prometheus configuration file
  become: true
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ service_root_path }}/{{ prometheus_name }}/prometheus.yml"
    mode: "0644"
  notify:
    - Restart prometheus service

# Create prometheus alerting rules file
- name: Create prometheus alerting rules files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ service_root_path }}/{{ prometheus_name }}/alerts/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "*.yml"
  loop_control:
    label: "{{ item | basename }}"
  notify:
    - Restart prometheus service

# Create prometheus docker-compose file
- name: Create prometheus docker-compose file
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ service_root_path }}/{{ prometheus_name }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Start prometheus service
