---

- name: detect | services
  ansible.builtin.service_facts:

- name: detect | prometheus container
  community.docker.docker_container_info:
    name: '{{ prometheus_name }}'
  register: prometheus_container

- name: detect | prometheus container exists fact
  ansible.builtin.set_fact:
    prometheus_container_exists: '{{ true if prometheus_container.exists else false }}'

- name: detect | prometheus container update fact
  ansible.builtin.set_fact:
    prometheus_container_update: >
      {{ true if prometheus_container.exists and prometheus_tag not in prometheus_container.container.Config.Image else false }}

- name: detect | set node exporter targets
  ansible.builtin.set_fact:
    node_exporter_targets: >-
      {{ node_exporter_targets | default([]) + [node_exporter_targets | default([]) |
      combine([{"targets": [hostvars[item].ansible_host + ':' + hostvars[item].node_exporter_listening_port | string],
      "labels": {"instance": hostvars[item].inventory_hostname}}])] }}
  loop: '{{ groups["node_exporter"] }}'
  when:
    - '"servers" in group_names'
