---

galaxy_info:
  role_name: pihole
  namespace: flyoverhead
  author: flyoverhead
  description: Pi-hole docker service deployment
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - adblock
    - dns
    - docker
    - networking

dependencies: []
