---

# Torrserver configuration
# https://github.com/YouROK/TorrServer
# https://hub.docker.com/r/ksey/torrserver
torrserver_name: torrserver
torrserver_image: ksey/torrserver
torrserver_tag: latest
torrserver_path: /opt/docker/torrserver
torrserver_port: '8070'
torrserver_restart_policy: always
torrserver_network_mode: host
torrserver_timezone: Europe/Moscow
