---

- name: config | add users to docker group
  become: true
  ansible.builtin.user:
    name: '{{ item }}'
    groups: docker
    append: true
  loop: '{{ docker_users }}'
  notify:
    - docker | reload groups
    - docker | start service

- name: config | daemon.json
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - docker | restart service
