---

- name: install | clean unofficial packages
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: absent
    autoremove: true
    purge: true
  loop:
    - docker.io
    - docker-compose
    - docker-doc
    - podman-docker

- name: install | keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: install | dependencies
  become: true
  ansible.builtin.apt:
    name: '{{ docker_repo.requirements }}'
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: install | apt key
  become: true
  ansible.builtin.get_url:
    url: '{{ docker_repo.key }}'
    dest: /etc/apt/keyrings/docker
    mode: '0644'

- name: install | repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker] {{ docker_repo.url }}
    filename: docker
    state: present
    update_cache: true

- name: install | packages
  become: true
  ansible.builtin.apt:
    name: '{{ docker_repo.packages }}'
    state: present
    update_cache: true
    cache_valid_time: 3600
