---

- name: detect
  ansible.builtin.include_tasks:
    file: detect.yml

- name: install
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not docker_installed

- name: configure
  ansible.builtin.include_tasks:
    file: configure.yml

- name: handlers
  ansible.builtin.meta: flush_handlers
