---
# Service root path
service_root_path: "/opt/docker_services"

# Docker configuration
docker_restart_policy: "always"
docker_network_mode: "host"

# Default timezone
timezone: "Europe/Moscow"

# Drone CI configuration
# https://docs.drone.io/
# https://hub.docker.com/r/drone/drone
drone_name: "drone"
drone_image: "drone/drone"
drone_tag: "2.20.0"
drone_server_proto: "http"
drone_server_host: "{{ ansible_host }}"
drone_server_port: "8000"
drone_rpc_secret: "c8df9027745212b3b19416cc2247d9ce"
drone_admin_username: "drone"
drone_admin_token: "f553387083d88b9c3858be041cd31929"
drone_gitea_server: "http://{{ gitea_domain }}:{{ gitea_web_port }}"
drone_gitea_user_token: "{{ gitea_admin_token }}"
drone_db_type: "postgres"
drone_db_address: "{{ ansible_host }}:5432"
drone_db_name: "drone"
drone_db_user: "drone"
drone_db_password: "drone"
