---

# https://pi-hole.net/
# https://hub.docker.com/r/pihole/pihole/tags

pihole_docker_config:
  name: pihole
  image: pihole/pihole
  tag: 2024.07.0
  path: '{{ docker_path }}/pihole'
  restart_policy: '{{ docker_restart_policy }}'
  network_mode: '{{ docker_network_mode }}'
  timezone: '{{ docker_timezone }}'

pihole_service_config:
  dnsmasq_listening_address: all
  upstream_dns:
    - '{{ ansible_host }}#5353'
  web_password: pihole
  web_address: '{{ ansible_host }}'
  web_port: 8080
  dnssec: true
  query_logging: true
  dns_bogus_priv: true
  dns_fqdn_required: true
  web_theme: default-dark
  ipv6_support: false

pihole_lists:
  adlist: "{{ lookup('file', 'adlist.list') | split | length + 1 }}"
  domain_blacklist: "{{ lookup('file', 'domain_black.list') | split | length }}"
  domain_whitelist: "{{ lookup('file', 'domain_white.list') | split | length }}"

pihole_required_packages:
  - sqlite3
