---
# Check current postgres service if exists
- name: Check postgres container
  community.docker.docker_container_info:
    name: "{{ postgres_name }}"
  register: postgres_service
  changed_when: >
    not postgres_service.exists or
    postgres_tag not in postgres_service.container.Config.Image
  failed_when: postgres_service.exists and postgres_service.container.State.ExitCode != 0
  notify:
    - Start postgres service

# Configure postgres service
- name: Configure postgres service
  ansible.builtin.include_tasks: configure.yml

# Deploy postgres service
- name: Deploy postgres service
  ansible.builtin.meta: flush_handlers
