---

- name: prometheus | start container
  community.docker.docker_compose_v2:
    project_src: '{{ prometheus_docker_config.path }}'
    state: present
    wait: true
    wait_timeout: 60

- name: prometheus | restart container
  become: true
  community.docker.docker_compose_v2:
    project_src: '{{ prometheus_docker_config.path }}'
    state: restarted
    wait: true
    wait_timeout: 60
