---
# Create wireguard client configuration file
- name: Create wireguard client configuration file
  when: inventory_hostname in item
  block:
    # Read wireguard client configuration file
    - name: Read wireguard configuration file for {{ item }}
      delegate_to: "{{ groups['vpn_server'] | first }}"
      become: true
      ansible.builtin.slurp:
        src: "{{ service_root_path }}/{{ wireguard_name }}/config/peer_{{ item }}/peer_{{ item }}.conf"
      register: wireguard_client_config

    # Create wireguard client configuration file
    - name: Create wireguard configuration for {{ item }}
      become: true
      ansible.builtin.copy:
        content: "{{ (wireguard_client_config.content | b64decode) | trim }}"
        dest: "{{ service_root_path }}/{{ wireguard_name }}/config/wg0.conf"
        mode: "0644"
      notify:
        - Restart wireguard service

    # Create wireguard docker-compose file
    - name: Create wireguard docker-compose file for {{ item }}
      become: true
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "{{ service_root_path }}/{{ wireguard_name }}/docker-compose.yml"
        mode: "0644"
      notify:
        - Start wireguard service

    # Deploy wireguard service in client mode
    - name: Deploy wireguard service
      ansible.builtin.meta: flush_handlers
