---

- name: detect | services
  ansible.builtin.service_facts:

- name: detect | wireguard container
  community.docker.docker_container_info:
    name: '{{ wireguard_name }}'
  register: wireguard_container

- name: detect | wireguard container exists fact
  ansible.builtin.set_fact:
    wireguard_container_exists: '{{ true if wireguard_container.exists else false }}'

- name: detect | wireguard container update fact
  ansible.builtin.set_fact:
    wireguard_container_update: >
      {{ true if wireguard_container.exists and wireguard_tag not in wireguard_container.container.Config.Image else false }}
