---

- name: detect
  ansible.builtin.include_tasks:
    file: detect.yml

- name: install
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not wireguard_container_exists

- name: update
  ansible.builtin.include_tasks:
    file: update.yml
  when:
    - wireguard_container_update

- name: handlers
  ansible.builtin.meta: flush_handlers
