---
# Check current wireguard service if exists
- name: Check wireguard container
  community.docker.docker_container_info:
    name: "{{ wireguard_name }}"
  register: wireguard_service
  changed_when: >
    not wireguard_service.exists or
    wireguard_tag not in wireguard_service.container.Config.Image
  failed_when: wireguard_service.exists and wireguard_service.container.State.ExitCode != 0
  notify:
    - Start wireguard service

# Install wireguard service
- name: Prepare wireguard environment
  ansible.builtin.include_tasks: prepare.yml

# Configure wireguard server
- name: Configure wireguard server
  when: "'vpn_server' in group_names"
  ansible.builtin.include_tasks: server.yml

# Configure wireguard clients
- name: Configure wireguard clients
  when: "'vpn_clients' in group_names"
  ansible.builtin.include_tasks: client.yml
  loop: "{{ wireguard_peers }}"
  loop_control:
    label: "{{ item }}"
