---
# Create wireguard docker-compose file
- name: Create wireguard server docker-compose file
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ service_root_path }}/{{ wireguard_name }}/docker-compose.yml"
    mode: "0644"
  notify:
    - Start wireguard service

# Deploy wireguard service in server mode
- name: Deploy wireguard server
  ansible.builtin.meta: flush_handlers

# Add post up and down commands to clients configuration
- name: Add post up and down commands for clients
  become: true
  ansible.builtin.blockinfile:
    path: "{{ service_root_path }}/{{ wireguard_name }}/config/peer_{{ item }}/peer_{{ item }}.conf"
    block: |
      PostUp = {{ wireguard_post_up }}
      PostDown = {{ wireguard_post_down }}
    insertbefore: "^\\[Peer]"
    marker: "# {mark} PostUP and PostDown commands block"
  loop: "{{ wireguard_peers }}"
  loop_control:
    label: "{{ item }}"
