---

- name: update | wireguard docker-compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ wireguard_path }}/docker-compose.yml'
    mode: '0644'
    lstrip_blocks: true
  notify:
    - wireguard | restart container
