---
# Configure pihole domain blacklist
- name: Check pihole domain blacklist
  become: true
  ansible.builtin.command:
    cmd: sqlite3 {{ service_root_path }}/{{ pihole_name }}/data/gravity.db "SELECT COUNT(*) FROM domainlist WHERE type='3'"
  register: pihole_domain_blacklist
  changed_when: pihole_domain_blacklist.stdout != pihole_domain_blacklist_content
  notify:
    - Clean pihole blacklist
    - Configure pihole domain blacklist

# Configure pihole domain whitelist
- name: Check pihole domain whitelist
  become: true
  ansible.builtin.command:
    cmd: sqlite3 {{ service_root_path }}/{{ pihole_name }}/data/gravity.db "SELECT COUNT(*) FROM domainlist WHERE type='2'"
  register: pihole_domain_whitelist
  changed_when: pihole_domain_whitelist.stdout != pihole_domain_whitelist_content
  notify:
    - Clean pihole whitelist
    - Configure pihole domain whitelist

# Configure pihole adlist
- name: Check pihole adlist
  become: true
  ansible.builtin.command:
    cmd: sqlite3 {{ service_root_path }}/{{ pihole_name }}/data/gravity.db "SELECT COUNT(*) FROM adlist"
  register: pihole_adlist
  changed_when: pihole_adlist.stdout != pihole_adlist_content
  notify:
    - Configure pihole adlist
    - Update pihole gravity
