---

- name: detect | services
  ansible.builtin.service_facts:

- name: detect | pihole container
  community.docker.docker_container_info:
    name: '{{ pihole_name }}'
  register: pihole_container

- name: detect | pihole container exists fact
  ansible.builtin.set_fact:
    pihole_container_exists: '{{ true if pihole_container.exists else false }}'

- name: detect | pihole container update fact
  ansible.builtin.set_fact:
    pihole_container_update: >
      {{ true if pihole_container.exists and pihole_tag not in pihole_container.container.Config.Image else false }}
