---

galaxy_info:
  role_name: docker
  namespace: flyoverhead
  author: flyoverhead
  description: Docker engine installation and configuration
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - containers
    - docker
    - services

dependencies: []
